version: '3.7'
services:
  #######################################
  # Database
  #######################################
  task-database:
    image: mariadb:10.7.1-focal
    container_name: task-database
    restart: on-failure
    volumes:
      - db_data:/var/lib/mysql
      - ./init-database:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root_task
      MYSQL_USER: task
      MYSQL_PASSWORD: task
      MYSQL_DATABASE: task
    ports:
      - "23306:3306"
    networks:
      - task-net
  #######################################
  # Task
  #######################################
  task-nginx:
    container_name: task-nginx
    image: nginx:stable-alpine
    restart: on-failure
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../task:/var/www/html
    networks:
      - task-net
    links:
      - task
    ports:
      - "80:80"
  task:
    container_name: task
    build:
      context: .
      dockerfile: ./php/Dockerfile
    restart: on-failure
    volumes:
      - ../task:/var/www/html
    networks:
      - task-net
    links:
      - task-database

networks:
  task-net:
    driver: bridge

volumes:
  db_data:
    driver: local
